// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzupbllxgtobpykyerbi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6dXBibGx4Z3RvYnB5a3llcmJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzMDc1NzMsImV4cCI6MjA2MTg4MzU3M30.9tDG4QTuNe756gQ9qpENhkYawoAd5JzKmOVnvvH9TZ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);